package com.battleboats.data;
// Generated Oct 26, 2015 4:16:29 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Navy generated by hbm2java
 */
@Entity
@Table(name = "NAVY", schema = "BATTLEBOATS")
@XmlType(propOrder={
		"id",
		"budget",
		"player"
})
@XmlRootElement
public class Navy implements java.io.Serializable {

	
	private Integer id = -1;
	
	private Integer budget;
	private Integer player;

	public Navy() {
	}

	public Navy(int id) {
		this.id = id;
	}

	public Navy(int id, Integer budget, Integer player) {
		this.id = id;
		this.budget = budget;
		this.player = player;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "BUDGET", precision = 5, scale = 0)
	public Integer getBudget() {
		return this.budget;
	}

	public void setBudget(Integer budget) {
		this.budget = budget;
	}

	@Column(name = "PLAYER")
	public Integer getPlayer() {
		return this.player;
	}

	public void setPlayer(Integer player) {
		this.player = player;
	}

}
